name: dating
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  audio_recorder: ^1.0.2
  audioplayers: ^0.17.2
  basic_utils:
  cached_network_image: ^2.1.0+1
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  cryptography: ^1.4.1
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_messaging: ^6.0.16
  firebase_storage: ^5.2.0
  file: ^5.2.1
  flutter_secure_storage: ^3.3.5
  flutter_spinkit: ^4.1.2
  geoflutterfire: ^2.2.1
  http: ^0.12.1
  image_picker: ^0.6.5
  in_app_purchase: ^0.3.4+1
  intl: ^0.16.1
  intl_phone_number_input: ^0.5.2+2
  latlong: ^0.6.1
  location: ^3.0.0
  mime: ^0.9.7
  page_view_indicators: ^1.3.1
  path_provider: ^1.6.7
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  pin_code_fields: ^5.2.0
  progress_dialog: ^1.2.2
  provider: ^4.3.2+3
  settings_ui: ^0.5.0
  shared_preferences: ^0.5.6
  smooth_page_indicator: ^0.2.0
  url_launcher: ^5.7.2
  uuid: ^2.0.4
  video_player: ^0.11.0
  video_thumbnail: ^0.2.1

  gecies:
    git: git@github.com:nigeltiany/gecies.git

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/