name: dating
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  cryptography: ^1.4.1
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_messaging: ^6.0.16
  firebase_storage: ^5.2.0
  file: ^5.2.1
  flutter_secure_storage: ^3.3.5
  flutter_sound:
    git:
      url: git@github.com:nigeltiany/tau.git
      path: flutter_sound
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.18.1
  flutter_swiper: ^1.1.6
  geoflutterfire: ^2.2.1
  http: ^0.12.2
  image_picker: ^0.6.7+22
  latlong: ^0.6.1
  location: ^3.2.4
  mime: ^0.9.7
  native_updater: ^0.0.4
  new_version: ^0.0.6
  page_view_indicators: ^1.4.1
  path_provider: ^1.6.7
  photo_view: ^0.10.3
  progress_dialog: ^1.2.2
  provider: ^4.3.2+3
  simple_html_css: ^2.0.2
  settings_ui: ^0.5.0
  shared_preferences: ^0.5.6
  shimmer: ^1.1.2
  smooth_page_indicator: ^0.2.0
  uuid: ^2.2.2
  # video_player: ^1.0.1
  # video_thumbnail: ^0.2.5+1

  gecies:
    git:
      url: git@github.com:nigeltiany/gecies.git
      ref: 70f63841f4912bd8da9734d372cab121356a161d

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/